module:
  add_content_by_bundle: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_markdown: 0
  components: 0
  contact: 0
  content_sync: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_browser: 0
  entitygroupfield: 0
  field: 0
  field_layout: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  front_page: 0
  fullcalendar_view: 0
  gin_toolbar: 0
  gnode: 0
  group: 0
  groupmedia: 0
  image: 0
  inline_form_errors: 0
  l10n_client_contributor: 0
  language: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  radix_layouts: 0
  responsive_image: 0
  serialization: 0
  smart_date: 0
  smart_date_calendar_kit: 0
  smart_date_recur: 0
  smart_date_starter_kit: 0
  system: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  variationcache: 0
  views_ui: 0
  webprofiler: 0
  xmlrpc: 0
  views: 10
  minimal: 1000
theme:
  stable: 0
  classy: 0
  radix: 0
  claro: 0
  gin: 0
  gmwe_theme: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: hu
