label: 'Group Media'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      fields:
        name:
          label: 'Media name'
          separator: ', '
        bundle:
          label: Bundle
          separator: ', '
        status:
          label: Status
          separator: ', '
        uid:
          label: Publisher
          separator: ', '
        view_group_content:
          label: 'View relation link'
          text: 'View relation'
        edit_group_content:
          label: 'Edit relation link'
          text: 'Edit relation'
        delete_group_content:
          label: 'Delete relation link'
          text: 'Delete relation'
        edit_media:
          label: 'Edit media'
          text: Edit
        delete_media:
          label: 'Delete Media'
          text: Delete
        dropbutton:
          label: Dropbutton
      filters:
        status:
          expose:
            label: Status
          group_info:
            label: Status
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        bundle:
          expose:
            label: 'Media type'
      title: 'Group Media'
      arguments:
        gid:
          exception:
            title: All
          title: '{{ arguments.gid|placeholder }} media items'
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Media
