label: Címlap
description: 'A kezdőlapon közzétett összes tartalom.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Alkalmaz
          reset_button_label: Alaphelyzet
          exposed_sorts_label: Rendezés
          sort_asc_label: Növekvő
          sort_desc_label: Csökkenő
      pager:
        options:
          expose:
            items_per_page_label: 'Elemek száma oldalanként'
            items_per_page_options_all_label: '– Mind –'
            offset_label: Eltolás
          tags:
            previous: '‹ Előző'
            next: 'Következő ›'
            first: '« Első'
            last: 'Utolsó »'
    display_title: Mester
  feed_1:
    display_title: Hírcsatorna
